# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Ecache < Formula
  desc ""
  homepage "https://github.com/envoy/ecache"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envoy/ecache/releases/download/v0.1.0/ecache_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "69b472502b1c1b580a95a2884380c60732f1fffdc9223a10eb8878c768bd1501"

      define_method(:install) do
        bin.install "ecache"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envoy/ecache/releases/download/v0.1.0/ecache_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f39cd4422b4f9b85b5ea798d7f8d544f6bccf41537a902b2e6c081c895bef830"

      define_method(:install) do
        bin.install "ecache"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/ecache/releases/download/v0.1.0/ecache_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "72e39027613c9f32bace6a384fa91d860309aaa215b3f6b440514522bc9f3af9"
      define_method(:install) do
        bin.install "ecache"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/ecache/releases/download/v0.1.0/ecache_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7a5b2622cb50df5a6b81265b92496bfdbeccda8f7fd71fabcfd602b4844789cf"
      define_method(:install) do
        bin.install "ecache"
      end
    end
  end
end
