# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Ekafka < Formula
  desc ""
  homepage "https://github.com/envoy/ekafka"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envoy/ekafka/releases/download/v0.0.1/ekafka_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8462335571c7a2ef346aef1e4b0974dd854e45e856a69f50e828b4f2ce2f4ece"

      define_method(:install) do
        bin.install "ekafka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envoy/ekafka/releases/download/v0.0.1/ekafka_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b8f7c0664b6df3558905b50596b414dd8edef5d1ac7c7d0ddcc64732e38e9826"

      define_method(:install) do
        bin.install "ekafka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/ekafka/releases/download/v0.0.1/ekafka_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2ae04a60423224d77dbd976193b59492bc56e87a4f24bb35d43cb590ab4e0836"
      define_method(:install) do
        bin.install "ekafka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/ekafka/releases/download/v0.0.1/ekafka_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c8adec4b471794bde3a3f6d7dc7229553d61e6d44f26607abd9bfbccfbe0a0c1"
      define_method(:install) do
        bin.install "ekafka"
      end
    end
  end
end
