# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Emd < Formula
  desc "Wrapper for mirrord dev tool"
  homepage "https://github.com/envoy/homebrew-tools"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envoy/emd/releases/download/v0.0.5/emd_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "92e6fef26058593bc74041a9c5e7daae98b7a86c9e3d898d5dc939cbbdba4f06"

      def install
        bin.install "emd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envoy/emd/releases/download/v0.0.5/emd_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "72cc4124d69d5c6d4131245b68e2b129551f41527a506de492b54781b74380df"

      def install
        bin.install "emd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/emd/releases/download/v0.0.5/emd_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b8ccbb6e14c9a5d8b7d0fe6d74e4693d497f42fc1b5aaa0582052a25e83fdf74"
      def install
        bin.install "emd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/emd/releases/download/v0.0.5/emd_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3d661c5bf53610df212f74017401fe895b2b74272e791aa76e1826386f10cd46"
      def install
        bin.install "emd"
      end
    end
  end
end
