# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Emd < Formula
  desc "Wrapper for mirrord dev tool"
  homepage "https://github.com/envoy/homebrew-tools"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envoy/emd/releases/download/v0.0.2/emd_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7ecfc0500382aef07d68f25de4224b63fedd3ca34c167df826881bb9a8747b5d"

      def install
        bin.install "emd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envoy/emd/releases/download/v0.0.2/emd_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "46d901d3a2d56a87bfa8938941fa06d5b1de4e4bb6c2437005dca22f15cd9e51"

      def install
        bin.install "emd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/emd/releases/download/v0.0.2/emd_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1473c4868d4a3f16b71a150197fb9f5f64278775d18bc202773609df5aa8c913"
      def install
        bin.install "emd"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/emd/releases/download/v0.0.2/emd_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7c0f997909d62bacc94eaaf23526a5c8c48cf521d239a2f5b499409ccfdaba0d"
      def install
        bin.install "emd"
      end
    end
  end
end
