# typed: true
# frozen_string_literal: true

require_relative "lib/private_strategy"

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class EnvoyDevTools < Formula
  desc "Sets up developer tools"
  homepage "https://github.com/envoy/envoy-dev-tools"
  url "https://api.github.com/repos/envoy/envoy-dev-tools/tarball/v0.0.1", using: GitHubPrivateRepositoryReleaseDownloadStrategy
  sha256 "884d9936814a215bd229c68b0bf08d6a4074a10f2aead5ec7bb881098dafa0b2"

  depends_on "bash" => :build
  depends_on "docker-credential-helper-ecr"
  depends_on "jq"
  depends_on "okta-aws-cli"

  def install
    bin.install "envoy-dev-tools.sh" => "envoy-dev-tools"
  end

  test do
    system "#{bin}/envoy-dev-tools"
  end
end
