# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class EnvoyDevTools < Formula
  desc "Sets up developer tools for Envoy infrastructure"
  homepage "https://github.com/envoy/homebrew-tools"
  version "0.0.9"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/envoy/envoy-dev-tools/releases/download/v0.0.9/envoy-dev-tools_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "01df57f9689aab19fae23d9a000075d7b3dd077cc7bc4e802b9c4496b7686556"

    def install
      bin.install "envoy-dev-tools"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/envoy/envoy-dev-tools/releases/download/v0.0.9/envoy-dev-tools_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "ee7f0a47d0d092ec6f1b5a1aa3fbbb05b62fd719e6f48781e7dcb5258fe38c87"

    def install
      bin.install "envoy-dev-tools"
    end
  end

  def post_install
    ohai "Installation complete"
  end

  def caveats
    <<~EOS
      IMPORTANT: You must run `envoy-dev-tools` to complete the setup.

      The setup process will configure your environment for Envoy development.
      This may require modifying configuration files in your home directory.
    EOS
  end
end
