# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Esql < Formula
  desc ""
  homepage "https://github.com/envoy/esql"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envoy/esql/releases/download/v0.0.3/esql_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ba27d1f92a3c7788afa92e3ce13bbf15977f45c55384ab63f9f604516224ba02"

      define_method(:install) do
        bin.install "esql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envoy/esql/releases/download/v0.0.3/esql_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "874d51657a94c3f560f4c525a59bef5dd32f1973a0c5b4fb7bfd0367fb7a10df"

      define_method(:install) do
        bin.install "esql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/esql/releases/download/v0.0.3/esql_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1145026d8ad2d7baf73913ecebb9db8b94a0ad07822439f259682bb09bc5b979"
      define_method(:install) do
        bin.install "esql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/esql/releases/download/v0.0.3/esql_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5aa6d953c9a812b7b0a619d934c0bcc9731a95a6b230bb5210d61f2fac870b49"
      define_method(:install) do
        bin.install "esql"
      end
    end
  end
end
