# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Esql < Formula
  desc ""
  homepage "https://github.com/envoy/esql"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envoy/esql/releases/download/v0.0.2/esql_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2973acf9d5dc5d34f4d27d314d3ec05707e0eef19940f9f55dec6fabb8e427d2"

      define_method(:install) do
        bin.install "esql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envoy/esql/releases/download/v0.0.2/esql_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ccecfe25cc1470360ebf145c643d7c6074c616fb153b5847aa1e8d493a234a1e"

      define_method(:install) do
        bin.install "esql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/esql/releases/download/v0.0.2/esql_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "75a8e410791e6e35b6fc3fd59dbe16e0375fbc1b1d68b33d32ed4255891bf03b"
      define_method(:install) do
        bin.install "esql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/esql/releases/download/v0.0.2/esql_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f073cae6e693a8e32dab107c70c9c9577a8b24b3b9cc8230427a6241e8da5f1f"
      define_method(:install) do
        bin.install "esql"
      end
    end
  end
end
