# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Eta < Formula
  desc ""
  homepage "https://github.com/envoy/homebrew-tools"
  version "2.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envoy/eta/releases/download/v2.1.5/eta_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "42544106bfc1702481ec4ed839352e83e23aa68f4f9583a57bb3d11ea91eed5e"

      define_method(:install) do
        bin.install "eta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envoy/eta/releases/download/v2.1.5/eta_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "81cbcfa9f32449bc6f31f10349ace42071c892548cd3f700bfc92f733c66fd27"

      define_method(:install) do
        bin.install "eta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/eta/releases/download/v2.1.5/eta_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8abe88a7798e4e60d55405d60a00daf17b67e364ac0f7c9a24c5664a1e879c9f"
      define_method(:install) do
        bin.install "eta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/eta/releases/download/v2.1.5/eta_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e79a80a45edb839e6c3e4e52fbe67c3e8d773e94ca963c00af3f6cf4cce16497"
      define_method(:install) do
        bin.install "eta"
      end
    end
  end
end
