# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Eta < Formula
  desc ""
  homepage "https://github.com/envoy/homebrew-tools"
  version "1.16"

  on_macos do
    on_intel do
      url "https://github.com/envoy/eta/releases/download/v1.16/eta_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bdc7975cc9bd392481eba8357b1234f5e9a95865eb52878c19182f2d53b385b0"

      def install
        bin.install "eta"
      end
    end
    on_arm do
      url "https://github.com/envoy/eta/releases/download/v1.16/eta_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1b53f300b084fc46b1c7089d3f94f757025808963c75feb7a9bec9f1029f4407"

      def install
        bin.install "eta"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/envoy/eta/releases/download/v1.16/eta_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "1f2a72c30495f70440f854ad9fdad901ab9e3838f8cccad0e255d75ed7daa808"

        def install
          bin.install "eta"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/envoy/eta/releases/download/v1.16/eta_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "334ea1fe6c334fd8339880ee196477a51d07d68fb9a2872c0ad4824aa3190188"

        def install
          bin.install "eta"
        end
      end
    end
  end
end
