# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Eta < Formula
  desc ""
  homepage "https://github.com/envoy/homebrew-tools"
  version "2.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envoy/eta/releases/download/v2.0.3/eta_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7c2efbb349f38bd8d9d6ca39894a9e76147ec0b4be58592d25632368967bb718"

      def install
        bin.install "eta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envoy/eta/releases/download/v2.0.3/eta_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2c4499dc6096741a0bdd60f5a0a344e5381d0b0bc6bf4dcb26a68c789584da69"

      def install
        bin.install "eta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/envoy/eta/releases/download/v2.0.3/eta_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "ff10f0c92c273daaecadf9feb6d8acff9e08da6db4c2334e2b7f298c95ed5913"

        def install
          bin.install "eta"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/envoy/eta/releases/download/v2.0.3/eta_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "c9c1282f2a8d0066f006fe6e6f749a2a4d3a6b75a3503a20be08fe29a6fcc899"

        def install
          bin.install "eta"
        end
      end
    end
  end
end
