# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Otsecret < Formula
  desc ""
  homepage "https://github.com/envoy/homebrew-tools"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envoy/otsecret/releases/download/v0.0.5/otsecret_0.0.5_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "99fd71b621673f6b6c771d6c008f2fe94803ba0d896dbcb1d6fbf3bdadc60cec"

      def install
        bin.install "otsecret"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envoy/otsecret/releases/download/v0.0.5/otsecret_0.0.5_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "80c3d1c5099f1e7210988279e9fd8d6329fcbab49da9122db8b5289ca1a9beb5"

      def install
        bin.install "otsecret"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/otsecret/releases/download/v0.0.5/otsecret_0.0.5_Linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2e64b89237c37565525b04a7ae77f6d97f64575e09463911a2447da530017722"

      def install
        bin.install "otsecret"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/envoy/otsecret/releases/download/v0.0.5/otsecret_0.0.5_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "43e5ae36e09dd0c5134ad1093b4cae7bcdc95cf74d05e552075843a74568c9f3"

      def install
        bin.install "otsecret"
      end
    end
  end
end
