# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Tsecret < Formula
  desc ""
  homepage "https://github.com/envoy/homebrew-tools"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/envoy/tsecret/releases/download/v0.0.1/tsecret_0.0.1_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ea796402bf58d6cd3961b852b651abc4143ad8e1d33b628b517c2af34cdd6214"

      def install
        bin.install "tsecret"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/envoy/tsecret/releases/download/v0.0.1/tsecret_0.0.1_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2a62e7e8585c81fc7aeb4aac8acdec17ab4b16efa135d2c780f85fb50fe60dec"

      def install
        bin.install "tsecret"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/envoy/tsecret/releases/download/v0.0.1/tsecret_0.0.1_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "67e0d61fc70055f2174257744ad0d3d6ebabf8a485a54d61bfbbb1569c2de967"

      def install
        bin.install "tsecret"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envoy/tsecret/releases/download/v0.0.1/tsecret_0.0.1_Linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "16a1417104f95a3c6672ff6403ad6a998316ab9bd57702410efdaf689264d20b"

      def install
        bin.install "tsecret"
      end
    end
  end
end
